### ISSUE TITLE
I like your tool, Could you update the reload tool?

### ISSUE THREAD

**Issue by dzdhome** [timendum/proxy-reload#1]
Hello Sir/Miss

Because of the update of Firefox. The tool of "proxy-reload" not work on the new version. Could you update the reload tool again. Thank you.

**Comment by timendum** [comment]
Hi,
Last time I looked the new Firefox APIs for extension did not provided the
mehtods for implemention the extension, but I can check now.

**Comment by timendum** [comment]
Firefox starting from v59 (now in beta) has a method to allow this extension.

I've already rewritten the extension and published the results, also on [Mozilla Addon](https://addons.mozilla.org/en-US/firefox/addon/reload-pac-button/).
