### ISSUE TITLE
Broken in 61.0b2 (64-bit)?

### ISSUE THREAD

**Issue by Brandhand** [timendum/proxy-reload#2]
When I press the button, I get in the Web-Console the following error message:
browser.browserSettings.proxyConfig is undefined      background.js:17

Is this fixable?

**Comment by timendum** [comment]
I've looked at the [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/proxyConfig) and the method seems to be ok.

I'm on beta and it's still 60, on 2018-05-09/10 I can check version 61

**Comment by timendum** [comment]
I managed to reproduce the problem, in the 61 release notes I did not anything regarding `proxyConfig`, so I've opened a [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1460516).

**Comment by timendum** [comment]
I've uploaded version [0.2.1](https://github.com/timendum/proxy-reload/releases/tag/0.2.1), it's in review on [AMO](https://addons.mozilla.org/firefox/addon/reload-pac-button/).

**Comment by Brandhand** [comment]
Thanks for the quick response and fix.
